apiVersion: v1
kind: Service
metadata:
  name: coredns-service-tcp-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "coredns-svc-lb"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    k8s-app: kube-dns
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-service-udp-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "coredns-svc-lb"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    k8s-app: kube-dns
