apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
    name: my-pod-2
spec:
  containers:
  - name: my-pod-2
    image: nginx:latest
    volumeMounts:
    - name: data
      mountPath: /app/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-pvc

